### ISSUE TITLE
Github Pages Builds Failing

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#14]
**Describe the bug**

Currently when merging/releasing a new version, CircleCi successfully builds the main portion of the project however it fails to force push to the orphaned gh-branch for publishing the demo/docs.

**To Reproduce**

Create a PR, merge PR then look at the CircleCi builds. Alternatively, can visit the following link to see failing builds in CircleCi - https://circleci.com/gh/intuit/LD-React-Components

**Expected behavior**

Releases will successfully push to the gh-pages branch and report back a passing build to Github.

**Comment by poorpaddy** [comment]
Issue of failing builds still occur after PR #15 .

**Comment by vvscode** [comment]
@poorpaddy  two questions (due to a fact that I can't see full logs and other details at https://circleci.com/gh/intuit/LD-React-Components/387 )

1) Do other tasks work? I'm asking because of `# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.`
2) Have you added credentials to git repo on circleci?

**Comment by poorpaddy** [comment]
@vvscode yes, all other tasks work and yes credentials are there.

**Comment by vvscode** [comment]
but I don't see any other task which pushes code to git, that's why I'm asking

**Comment by poorpaddy** [comment]
You have a good point. I can double check that.

**Comment by poorpaddy** [comment]
All the permissions look correct. It could be the same issue as seen here https://discuss.circleci.com/t/no-config-found-builds-marked-as-failed/24912
