### ISSUE TITLE
References not updated for extension changes

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#67]
**Describe the bug**

When a large majority of file extensions were changed from .js the references were not changed accordingly.

Example: https://github.com/intuit/LD-React-Components/blob/4124c21c6e73867bf91cc324dadf52c8df150227/API/index.js#L1
However what ends up in dist is `/dist/LaunchDarklyClient/index.ts`.

I believe this is also affecting import references that assume .js and not .ts extensions such as `import FeatureCase from '../FeatureCase';`.

Also package.json references index.js that doesn't exist. https://github.com/intuit/LD-React-Components/blob/4124c21c6e73867bf91cc324dadf52c8df150227/package.json#L5

**Comment by erwintj** [comment]
@poorpaddy When I pull the repo and build `dist/index.js` does exist for me. Also, from what I can tell it seems that omitting the extension shouldn't break the importing of `.ts` files (https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules) because `moduleResolution` is set to `node` in `tsconfig.json`.

What's leading you to believe the imports without extension aren't working?

Opening a PR for the explicit reference in `LD-React-Components/API/index.js`.

**Comment by poorpaddy** [comment]
@erwintj trying installing it as a node module into a project. What you will see is quite different. Than if you do a build of this locally as a stand-alone.

**Comment by poorpaddy** [comment]
@erwintj See the output of the plugin installed in a client. The clients seem to not find anything in the dist that now has a .ts extension.
<img width="319" alt="Screen Shot 2019-10-31 at 11 08 37 AM" src="https://user-images.githubusercontent.com/2213076/67974206-41aa6980-fbcf-11e9-8abf-5c49b7f12dce.png">
<img width="966" alt="Screen Shot 2019-10-31 at 11 10 50 AM" src="https://user-images.githubusercontent.com/2213076/67974208-41aa6980-fbcf-11e9-8365-dd23a0b1e180.png">

**Comment by prashjain309** [comment]
is this still active for hactober @poorpaddy ?

**Comment by poorpaddy** [comment]
@prashjain309 yes it is. The bug is still occurring.

**Comment by poorpaddy** [comment]
@prashjain309 only a couple hours left for Hactoberfest.

**Comment by poorpaddy** [comment]
Outdated PR, no longer an issue
